### ISSUE TITLE
Solar Panels, Deployable ladders, RCS are not correctly displayed

### ISSUE THREAD

**Issue by OnlyLightMatters** [Kerbas-ad-astra/KronalVesselViewer#13]
There are a few bugs when rendering some parts.
They can be completely transparent and display the backgroud color whereas they should not.

Please find a screen capture to illustrate the issue.
Note that the Restock mod has been installed.
![screenshot38](https://user-images.githubusercontent.com/48958923/99183663-c6feae80-273d-11eb-9299-855452a40b71.png)

**Comment by Kerbas-ad-astra** [comment]
The issue turned out to be that KVV and ReStock were both tinkering with shaders (ReStock does it to get the 'depth mask' effect, where it looks like e.g. the ladders actually sink into the fuel tank instead of just overlapping with them, while KVV did it to achieve some drawing-like effects in previous versions -- a feature I disabled in the course of bringing KVV up to date for KSP 1.8).  Because that is no longer necessary in KVV, I've disabled those methods and now they work together!
